### ISSUE TITLE
Locking features

### ISSUE THREAD

**Issue by istvanrath** [FTSRG/mondo-collab-framework#27]
* enforcement (server lens)
* lock management (client)

**Comment by bergmanngabor** [comment]
Locking is now enforced by the newest lens version in master. 

I have played around a bit and found that it correctly denies a putback attempt if it would violate a lock, unless the change is performed by one of the owners of the lock.

@debrecenics The optional command line parameter `-mpbl <path> ` has been added to the offline lens CLI/daemon/invoker, that you can use to specify a single lock file. Currently, the same set of eiq files will be used for loading queries for both the .macl and the .mpbl files.
