### ISSUE TITLE
Minor corrections to the October 2015 Demo

### ISSUE THREAD

**Issue by istvanrath** [FTSRG/mondo-collab-framework#3]
* don't use "original", "gold" in file names
* make sure all rule definitions and EIQ patterns can be demoed in Eclipse
* create a script for modifying models, do not use pre-made model files
* add comments to the EIQ
* avoid showing the IllegalStateException, make error display nicer

**Comment by istvanrath** [comment]
Csabi, what is the progress on this one?

**Comment by debrecenics** [comment]
Currently, I am working on it. I am going to finish it for tomorrow.

**Comment by istvanrath** [comment]
Done.
