### ISSUE TITLE
Provide Eclipse RCP front-end for MONDO server management features

### ISSUE THREAD

**Issue by istvanrath** [FTSRG/mondo-collab-framework#40]
Related to #37 

Required features:
* [x] "get my front repo URL"
* [ ] "reset front repositories from gold"
* [x] "get online collaboration endpoint URL and launch browser"
* [x] facilities to add MONDO server endpoints, together with user-password credentials (to be stored locally via the Eclipse Secure Storage)

**Comment by bergmanngabor** [comment]
> "force-reload MACL configuration on server"

MACL is now simply a part of the repository, and evaluated each time a lens operation is performed, so this operation is not meaningful right now. We can add it later if we introduce various optimizations to the lens that actually caches MACL contents.

**Comment by istvanrath** [comment]
As discussed with @imbur, we think that an additional feature to access the online collaboration endpoint URL and (optionally) launch the default browser on it.

**Comment by imbur** [comment]
Features added.

**Comment by imbur** [comment]
Reopening this issue, for the reset operation does not comply its specification.
