### ISSUE TITLE
Update mondo.inf.mit.bme.hu with new results

### ISSUE THREAD

**Issue by istvanrath** [FTSRG/mondo-collab-framework#41]
* [ ] set up offline lens daemon #36 
* [x] deploy newest version of online tool

**Comment by debrecenics** [comment]
I exported the latest version of the online tool and uploaded to the server: http://mondo.inf.mit.bme.hu/web/mondo-wt-demo/online/

**Comment by debrecenics** [comment]
However, the tycho build has to be fixed because it fails.

**Comment by debrecenics** [comment]
The build process is stable again.
