### ISSUE TITLE
Integrate locking to online demo

### ISSUE THREAD

**Issue by istvanrath** [FTSRG/mondo-collab-framework#49]
- [x] test whether lock description files can be opened, edited and parsed in the RAP environment (edited at least as plain text, parsed as EMF models using Xtext runtime)
- [x] make sure online lens has a "reinitialize locks" functionality ( @bergmanngabor )
- [x] integrate lock operations into online editors (e.g. correctly display "denied" errors in case a lock violation is detected)
- [x] integrate lock editing operations into online demo (e.g. when saving the lock def file, locks are re-initialized)
- [x] create log messages for applied locks

**Comment by debrecenics** [comment]
Unfortunately, RAP does not support Xtext editors. However this looks promising: http://dslforge.org/

**Comment by istvanrath** [comment]
please use plain text editors if possible.

**Comment by imbur** [comment]
Changes are on the 'lens-online-reinitalizable' branch. The last missing task might need some debugging, so leaving that open until I get some feedback on that part.

**Comment by imbur** [comment]
It was reopened for the same reason why #52 exists. Closing, advances on the topic can be followed under the referenced ticket.
