### ISSUE TITLE
Editor stays dirty and shows extra content after commit

### ISSUE THREAD

**Issue by imbur** [FTSRG/mondo-collab-framework#52]
When performing a commit in the online collaboration editor, the other editors of other users should update dirty flag and content accordingly.

**Comment by bergmanngabor** [comment]
This issue was reproduced again by @istvanrath.
I have pushed some more logging code, hoping it may help in isolating the issue.
We will try to triangulate the problem next week with @imbur.

**Comment by imbur** [comment]
There are two different tasks to complete:
- [ ] ensure that the dirty bit is in line with the state of the content
- [ ] fix lens reinitialization issue

**Comment by imbur** [comment]
Could not reproduce this phenomenon after the previous fix. Closing.
